.TH Lb_1.1 1
.SH NAME
Lb_1.1 \- программа для выполнения операций с массивом чисел из файла
.SH SYNOPSIS
.B Lb_1.1
.RI [ --input " входной_файл" ]
.RI [ --output " выходной_файл" ]
.RI [ --operation " операция" ]
.RI [ --help ]
.SH DESCRIPTION
Программа выполняет одну из операций над массивом чисел, прочитанных из входного файла, и сохраняет результат в выходной файл. Поддерживаются следующие операции:
- Сортировка чисел по возрастанию,
- Реверс (обратный порядок) чисел,
- Перестановка элементов на чётных и нечётных позициях.
.PP
.SH OPTIONS
.TP
.B --input
Указывает путь к входному файлу, содержащему массив целых чисел (не более 100 чисел).
.TP
.B --output
Указывает путь к выходному файлу, в который будет сохранён результат выполнения операции.
.TP
.B --operation
Указывает операцию, которую нужно выполнить над массивом чисел.
Поддерживаются следующие значения:
.IP
- .B sort
: сортировка чисел по возрастанию;
.IP
- .B reverse
: обратный порядок чисел;
.IP
- .B swap
: перестановка чисел на чётных и нечётных позициях.
.TP
.B --help
Выводит справку по использованию программы, описывающую доступные ключи и аргументы.
.SH EXAMPLES
.TP
Выполнить сортировку массива чисел:
.B Lb_1.4 --input входной.txt --output результат.txt --operation sort
.TP
Выполнить реверс массива чисел:
.B Lb_1.4 --input входной.txt --output результат.txt --operation reverse
.TP
Выполнить перестановку чисел на чётных и нечётных позициях:
.B Lb_1.4 --input входной.txt --output результат.txt --operation swap
.SH EXIT STATUS
.TP
0: Программа завершилась успешно.
.TP
1: Ошибка выполнения (например, ошибка открытия файла или неизвестная операция).
.SH FILES
.TP
.B liboperations.so
Динамическая библиотека, содержащая реализацию операций сортировки, реверса и перестановки.
.SH BUGS
Программа ограничена массивами, содержащими не более 100 элементов. Если входной файл содержит больше чисел, программа завершится с ошибкой.
.SH AUTHOR
damer-Vega 

